/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: n- (https://sketchfab.com/n-)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crystal-jellyfish-leptomedusae-38ac0d91213d447eb3366f615298ce8f
title: Crystal Jellyfish (Leptomedusae)
//  npx gltfjsx crystal_jellyfish_leptomedusae.glb  
https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { act } from '@react-three/fiber';
import { Select } from '@react-three/postprocessing';

export function Jellyfish1(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    '/models/crystal_jellyfish_leptomedusae.glb'
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    const animationAction = actions['200'];
    animationAction.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh
        enabled={true}
        name="Object_7"
        geometry={nodes.Object_7.geometry}
        material={materials['Crystal-jelly_tentacle']}
        material-color={'aquamarine'}
        skeleton={nodes.Object_7.skeleton}
        receiveShadow={false}
      />
      <skinnedMesh
        name="Object_8"
        enabled={true}
        geometry={nodes.Object_8.geometry}
        material={materials['Crystal-jelly_bell1']}
        skeleton={nodes.Object_8.skeleton}
        material-color={'hotpink'}
        receiveShadow={false}
      />
      <skinnedMesh
        enabled={true}
        name="Object_9"
        geometry={nodes.Object_9.geometry}
        material={materials['Crystal-jelly_bell2']}
        material-color={[2, 1.75, 0]}
        emissive={[2, 1.75, 0]}
        emissiveIntensity={100.1}
        toneMapped={false}
        skeleton={nodes.Object_9.skeleton}
        receiveShadow={false}
      />
    </group>
  );
}

useGLTF.preload('/models/crystal_jellyfish_leptomedusae.glb');
