/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BlueMesh (https://sketchfab.com/VapTor)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/great-white-shark-b67415aaa0bd450d865f9604dcdac244
title: Great White Shark
npx gltfjsx great_white_shark.glb 
*/
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DigitalLife3D (https://sketchfab.com/DigitalLife3D)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/model-54a-caribbean-reef-shark-210302e0e0e74c36834fb00aaa14c7c2
title: Model 54A - Caribbean Reef Shark
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Shark(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    '/models/caribbean_reef_shark.glb'
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log('actions', actions.Action);
    const animationAction = actions.Action;
    animationAction.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={10}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Carribean_Reef_Shark_Armature_33"
                position={[0.17, 0, 0]}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Carribean_Reef_Shark_32" />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Diffuse_Eye}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.CRS_Material}
                    skeleton={nodes.Object_8.skeleton}
                    castShadow
                    
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/caribbean_reef_shark.glb');
